kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gcp-project-operator
  annotations:
    package-operator.run/phase: rbac
    package-operator.run/collision-protection: IfNoController
subjects:
- kind: ServiceAccount
  name: gcp-project-operator
  namespace: gcp-project-operator
roleRef:
  kind: ClusterRole
  name: gcp-project-operator
  apiGroup: rbac.authorization.k8s.io
